"""initial migration

Revision ID: 2580dd9569e7
Revises: 
Create Date: 2025-09-26 18:26:53.809027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2580dd9569e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_tokens_jti'), 'blacklisted_tokens', ['jti'], unique=True)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'EDITOR', 'MANAGER', 'ADMIN', 'NOT_SELECTED', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('volunteers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteers_id'), 'volunteers', ['id'], unique=False)
    op.create_index(op.f('ix_volunteers_phone_number'), 'volunteers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_volunteers_username'), 'volunteers', ['username'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_volunteer_id'), 'otp_verifications', ['volunteer_id'], unique=False)
    op.create_table('video_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.String(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('video_platform_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'PENDING_REVIEW', 'ACCEPTED', 'ASSIGNED', 'DECLINED', 'USED', name='submissionstatus'), nullable=False),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_submissions_telegram_file_id'), 'video_submissions', ['telegram_file_id'], unique=True)
    op.create_index(op.f('ix_video_submissions_volunteer_id'), 'video_submissions', ['volunteer_id'], unique=False)
    op.create_table('video_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_submission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_manager_id', sa.UUID(), nullable=False),
    sa.Column('assigned_editor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'REVISION_NEEDED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('completed_video_url', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('editor_notes', sa.String(), nullable=True),
    sa.Column('manager_notes', sa.String(), nullable=True),
    sa.Column('revision_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_editor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_submission_id'], ['video_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assignments_assigned_editor_id'), 'video_assignments', ['assigned_editor_id'], unique=False)
    op.create_index(op.f('ix_video_assignments_assigned_manager_id'), 'video_assignments', ['assigned_manager_id'], unique=False)
    op.create_index(op.f('ix_video_assignments_video_submission_id'), 'video_assignments', ['video_submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_assignments_video_submission_id'), table_name='video_assignments')
    op.drop_index(op.f('ix_video_assignments_assigned_manager_id'), table_name='video_assignments')
    op.drop_index(op.f('ix_video_assignments_assigned_editor_id'), table_name='video_assignments')
    op.drop_table('video_assignments')
    op.drop_index(op.f('ix_video_submissions_volunteer_id'), table_name='video_submissions')
    op.drop_index(op.f('ix_video_submissions_telegram_file_id'), table_name='video_submissions')
    op.drop_table('video_submissions')
    op.drop_index(op.f('ix_otp_verifications_volunteer_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_volunteers_username'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_phone_number'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_id'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_blacklisted_tokens_jti'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
