"""updated the assignment models

Revision ID: 2de57b994369
Revises: 3b2631496501
Create Date: 2025-09-20 17:59:02.216091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de57b994369'
down_revision: Union[str, Sequence[str], None] = '3b2631496501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_submission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_manager_id', sa.UUID(), nullable=False),
    sa.Column('assigned_editor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'REVISION_NEEDED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('completed_video_url', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('editor_notes', sa.String(), nullable=True),
    sa.Column('manager_notes', sa.String(), nullable=True),
    sa.Column('revision_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_editor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['video_submission_id'], ['video_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assignments_assigned_editor_id'), 'video_assignments', ['assigned_editor_id'], unique=False)
    op.create_index(op.f('ix_video_assignments_assigned_manager_id'), 'video_assignments', ['assigned_manager_id'], unique=False)
    op.create_index(op.f('ix_video_assignments_video_submission_id'), 'video_assignments', ['video_submission_id'], unique=False)
    op.drop_constraint(op.f('video_submissions_assigned_editor_id_fkey'), 'video_submissions', type_='foreignkey')
    op.drop_column('video_submissions', 'assigned_editor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_submissions', sa.Column('assigned_editor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('video_submissions_assigned_editor_id_fkey'), 'video_submissions', 'users', ['assigned_editor_id'], ['user_id'])
    op.drop_index(op.f('ix_video_assignments_video_submission_id'), table_name='video_assignments')
    op.drop_index(op.f('ix_video_assignments_assigned_manager_id'), table_name='video_assignments')
    op.drop_index(op.f('ix_video_assignments_assigned_editor_id'), table_name='video_assignments')
    op.drop_table('video_assignments')
    # ### end Alembic commands ###
