"""add_video_description_columns

Revision ID: 94346bdf26e4
Revises: 17e1a6029875
Create Date: 2025-10-01 10:47:20.624041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94346bdf26e4'
down_revision: Union[str, Sequence[str], None] = '17e1a6029875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_submissions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('video_submissions', sa.Column('telegram_message_id', sa.BigInteger(), nullable=True))
    op.add_column('video_submissions', sa.Column('submission_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_submissions', 'submission_metadata')
    op.drop_column('video_submissions', 'telegram_message_id')
    op.drop_column('video_submissions', 'description')
    # ### end Alembic commands ###
