"""updtaed the videosubmiison table with notification relted column

Revision ID: c6b2458b212b
Revises: df6e48ea1e7b
Create Date: 2025-09-20 10:38:17.583638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b2458b212b'
down_revision: Union[str, Sequence[str], None] = 'df6e48ea1e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_submissions', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.add_column('video_submissions', sa.Column('notification_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_submissions', 'notification_sent_at')
    op.drop_column('video_submissions', 'notification_sent')
    # ### end Alembic commands ###
